### ISSUE TITLE
Please add an example on how to reuse existing tokens

### ISSUE THREAD

**Issue by jensb** [nordigen/nordigen-ruby#7]
**Describe the solution you'd like**
I would like to be able to save authentication tokens so that my application does not have to visit Nordigen's or the bank's website each time the user wants to update their transactions. I am aware of the fact that this is required by the PSD2 system every 90 days, but it should not be required on every invocation of the app.

**Describe alternatives you've considered**
I have implemented a login flow as per the example, but I cannot get the login flow working with `client.set_token(...)` and an existing Refresh token, without *still* having to authorize my app by authenticating with the bank.

**Additional context**
Please add a specific example on how and what to store to be able to repeatedly access an account via Nordigen, without having to authenticate every time.

Thanks!

**Comment by victory-sokolov** [comment]
Hello.

You can check the Rails example application in the example directory.

Basically, after the user has been authenticated via bank you get a `requisition_id` then with this `requisition_id` you can access `account_id` via `client.requisition.get_requisition_by_id(requisition_id)["accounts"]`, then you have only to use this account_id to access data

So you should store this account_id somewhere and check if acces_token is not expired since it is valid for 24 hours after you have to refresh it.

Let me know if you have any questions.
